volumes :
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tarnaud/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/tarnaud/data/mariadb
      o: bind
      type: none
services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: on-failure
    networks:
      - inception
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: on-failure
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    expose:
      - "3306"
  nginx:
    container_name: nginx
    build: requirements/nginx/
    restart: on-failure
    env_file: .env
    ports:
      - "443:443"
networks:
  inception:
    name: inception
    driver: bridge
