volumes :
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/home/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/home/data/mariadb
      o: bind
      type: none
services:
  wordpress:
    container_name: wordpress
    build: ./wordpress/
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./nginx/
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    restart: unless-stopped
networks:
  inception:
    name: inception
    driver: bridge
